{"uuid": "cf9754ae-8a0e-4c95-9791-20f81c2951e8", "children": ["e18f3e3b-669e-41c0-af07-4033dcf22f52"], "befores": [{"name": "p_login", "status": "broken", "statusDetails": {"message": "requests.exceptions.SSLError: HTTPSConnectionPool(host='10.10.10.121', port=4500): Max retries exceeded with url: /UAMS/auth?username=qitingfei02 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))\n", "trace": "  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\D\\api_auto_test\\api_auto_test\\conftest.py\", line 44, in p_login\n    return login(user['username'])\n  File \"D:\\D\\api_auto_test\\api_auto_test\\conftest.py\", line 15, in login\n    resp = requests.request(method='POST',\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\adapters.py\", line 517, in send\n    raise SSLError(e, request=request)\n"}, "start": 1702887144851, "stop": 1702887144859}], "start": 1702887144851, "stop": 1702887144940}