[2024-01-11 16:10:01,544] [INFO] [test_01_workspace_mnt.py] [line 44] 插件管理-设置用户默认场景-用户id为空请求路径为:/OneHit/scene/default,请求体为:{}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\logging\handlers.py", line 70, in emit
    self.doRollover()
  File "C:\Program Files\Python38\lib\logging\handlers.py", line 171, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python38\lib\logging\handlers.py", line 111, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'D:\\D\\api_auto_test\\api_auto_test\\logs\\2024-01-11.log' -> 'D:\\D\\api_auto_test\\api_auto_test\\logs\\2024-01-11.log.1'
Call stack:
  File "D:/D/api_auto_test/api_auto_test/run.py", line 30, in <module>
    run_case()
  File "D:/D/api_auto_test/api_auto_test/run.py", line 22, in run_case
    pytest.main(['--alluredir', 'reports/allure-report'])
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\config\__init__.py", line 169, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\main.py", line 318, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\main.py", line 271, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\main.py", line 325, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\main.py", line 350, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 114, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 133, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 222, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 261, in call_runtest_hook
    return CallInfo.from_call(
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\D\api_auto_test\api_auto_test\tests\test_01_workspace_mnt.py", line 44, in test_01_workspace_mnt
    logger.info("{}请求路径为:{},请求体为:{}".format(datas["title"], datas["path"], datas["data"]))
Message: '插件管理-设置用户默认场景-用户id为空请求路径为:/OneHit/scene/default,请求体为:{}'
Arguments: ()
[2024-01-11 16:10:01,578] [INFO] [test_01_workspace_mnt.py] [line 77] 插件管理-设置用户默认场景-用户id为空状态码：500，响应结果:{"code":"INTERNAL_SERVER_ERROR","message":"服务器内部异常,请联系管理员"}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\logging\handlers.py", line 70, in emit
    self.doRollover()
  File "C:\Program Files\Python38\lib\logging\handlers.py", line 171, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Program Files\Python38\lib\logging\handlers.py", line 111, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'D:\\D\\api_auto_test\\api_auto_test\\logs\\2024-01-11.log' -> 'D:\\D\\api_auto_test\\api_auto_test\\logs\\2024-01-11.log.1'
Call stack:
  File "D:/D/api_auto_test/api_auto_test/run.py", line 30, in <module>
    run_case()
  File "D:/D/api_auto_test/api_auto_test/run.py", line 22, in run_case
    pytest.main(['--alluredir', 'reports/allure-report'])
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\config\__init__.py", line 169, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\main.py", line 318, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\main.py", line 271, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\main.py", line 325, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\main.py", line 350, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 114, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 133, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 222, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 261, in call_runtest_hook
    return CallInfo.from_call(
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\wangsihan\AppData\Roaming\Python\Python38\site-packages\_pytest\python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "D:\D\api_auto_test\api_auto_test\tests\test_01_workspace_mnt.py", line 77, in test_01_workspace_mnt
    logger.info("{}状态码：{}，响应结果:{}".format(datas["title"], resp.status_code, resp.text))
Message: '插件管理-设置用户默认场景-用户id为空状态码：500，响应结果:{"code":"INTERNAL_SERVER_ERROR","message":"服务器内部异常,请联系管理员"}'
Arguments: ()
