{"uuid": "aa695dae-6c95-4122-873a-0f5ec71a927a", "children": ["95ff1909-9d93-4235-94f4-18d5580e5539"], "befores": [{"name": "d_login", "status": "broken", "statusDetails": {"message": "requests.exceptions.SSLError: HTTPSConnectionPool(host='10.10.10.121', port=4500): Max retries exceeded with url: /UAMS/auth?username=qitingfei01 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))\n", "trace": "  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\D\\api_auto_test\\api_auto_test\\conftest.py\", line 35, in d_login\n    return login(user['username'])\n  File \"D:\\D\\api_auto_test\\api_auto_test\\conftest.py\", line 15, in login\n    resp = requests.request(method='POST',\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\adapters.py\", line 517, in send\n    raise SSLError(e, request=request)\n"}, "start": 1702887145867, "stop": 1702887145874}], "start": 1702887145867, "stop": 1702887145960}