{"uuid": "06544aee-1ef2-41e2-ae30-9e784ca4a5c4", "children": ["f0c739ff-9f12-4375-9056-29acc7edfbe2"], "befores": [{"name": "d_login", "status": "broken", "statusDetails": {"message": "requests.exceptions.SSLError: HTTPSConnectionPool(host='10.10.10.121', port=4500): Max retries exceeded with url: /UAMS/auth?username=qitingfei01 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))\n", "trace": "  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\D\\api_auto_test\\api_auto_test\\conftest.py\", line 35, in d_login\n    return login(user['username'])\n  File \"D:\\D\\api_auto_test\\api_auto_test\\conftest.py\", line 15, in login\n    resp = requests.request(method='POST',\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\adapters.py\", line 517, in send\n    raise SSLError(e, request=request)\n"}, "start": 1702887146567, "stop": 1702887146574}], "start": 1702887146567, "stop": 1702887146655}